### PR TITLE
Tailwindcss implementation

### PR DESCRIPTION
**Pull request by iagopiresdev**
### Tailwind css refactor

- Installed tailwind though the command `yarn add -D tailwindcss postcss autoprefixer`
- Created the config file though the command `yarn tailwindcss init -p`
- Added js and jsx as template paths.
- Added the tailwind directives in index.css
- Deleted most lines of code inside index.css to eliminate conflicts with tailwind
- Updated App and Header jsx files to include tailwind maintaining the same design

**This is only a preview of what tailwind is capable of, I let the original Header.css file only for comparison**

### CODE REVIEW

**Comment by guilhermemdasilva** [comment]
@iagopiresdev acredito que porque vc adicionou as dependências do tailwind com o npm, elas não foram adicionadas ao  ```yarn.lock```
teria como dar um comando ```yarn``` e subir o ```yarn.lock```?

**Comment by iagopiresdev** [comment]
Ops, falei npm no pull request porem usei yarn mesmo!

**Comment by iagopiresdev** [comment]
> Ops, falei npm no pull request porem usei yarn mesmo!

@guilhermemdasilva

**Review by guilhermemdasilva — APPROVED** [review]
LGTM!

**Pull request merged**
